language: node_js
cache: npm

service:
  - docker

install:
  - yarn install --frozen-lockfile
before_script:
  - yarn lint
  - docker pull $IMAGE_TAG
script:
  - docker build -t $IMAGE_TAG .


deploy:
  provider: script
  script: bash ./scripts/docker-push
  on:
    branch: master

env:
  global:
    - IMAGE_TAG=pietvanzoen/is-common-password:latest
    - secure: Nhkxo1ch30NFoWwhRcCXeVrYAput7cKfdxy/YdfBmA0LztlNz9G2DGgCDhtZxBhfOO2bKsFO4FAhnqx4L4XB3uoyzMGnnUJGH0M9tzWGJNbzkYrGgPkjl1IvdRW1N7j4j8Pbi0ZwFJDP90wFIYjyPkL+c0CDLGJWdSklmdtJ5K9GAqoH5H6lcGQK7DK6M+HvmzbCqpi2zPRYFIqv6OT3tJd1OV7JoW7YEU8VoZqzh1FUyUL6kkdrRtULyI4AgjISoB5tupI+t2cpl1hz3ICYJcno6CZ9qunfgdXKUn9Qfu8B43Llz+o2A7kpCsklbs3YX1h8fWES6nGNQvUAUYKsl9OkW249xu+a5022/S5UhskGwJdjNF84+5RgqHXklrE3WczI86W2j2B1PYTyW4t9ig441otaPTpqdnwnMyjUpM6xothO1bL3CAH4yJFAhVi5ERk+7agoRq6iNOdTSs+CaqM5tAQk161t0E4eFIDxXSIJQQViWhB1vmITDW+oRZTGLlX3/aDvW+n06nC5lhhjye3illuZf4lUqJQ13EzI/B9RJm8CnlTRleozhMS2ksR/JSLWXIAJ9B3QlcInAHTZ+HVoQMdqg/8FHYI3Ob1pyRfVP30Npe/qso4hVlvAojUdwEdyjy4b56aUtPve7xSg0xg+VtrDtlc5xsXSzqQFLZU=
    - secure: MUicAHXP30JuS9nfDI4nvdPnin+8rVoK8cDeMg14icZpHOaiZdNy/q3vVfHQtwJI/rCBv/tyTND6BdYFywYoTNAlDMMVrYCmPB0LNAuk/Ts+r3GiyFiNngrorGfaaoUHPsjRkAcNM5PWK9VAnITB6Vk5p15TNBM9FOLuNl2WpM1hHaaqv8DSiFWGHZCWlqXoXCSIVqWkfzWnF/e4D58t809zbCmjG+Ulg7rISEoUa9HLLEYuR/TnkB/8fO6JxX1BNHLFWbpTLNM2+szD2akUz9SQBw4XJdnnnXMsq0lPLa4qKzSt9f/lcv4jiXcDdBKe91gVIXHB6CSW+GLdpBjLBkt0eiGg6AaBXyp79GBgMXMQ0BHURCojxo6e9oLrsWYBzvKf3CBiFuMg3xTXhYhYAYgxw2H5Kifd0D8pl+Xo3P9Szu0DweNm2TBJRfjZLfMghJVtV38Bk72RZa3SMcXKp//GMywu9f0N57Lv31WWXzBM+flU1BR/kd6cpQIEdG9sYw8QBdDG21aN+gwXiM3Q7YDIOz+hNra3UoDFEhdQqRl0a2mVjSAXsLGrmYIGJeHr/M9heJNdoEdw2xF8C60d0R9SAp1hXBzXqc0RoZZnxzmvqyGkVUJ+fQnHDo6kW3pJ0iTgr16RxhkWHL80PI5WMdsdEzXt+2BH6hqcHNJ+N3U=
